/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package loft;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author paulyves
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }
    
    public void paintComponent(Graphics g) {
        int alea = (int)(Math.random() * 4);
        if (alea>1){
            g.setColor(Color.red);
        } else {
            g.setColor(Color.black);
        }
        for (int i = 0; i < Loft.W; i++) {
            for (int j = 0; j < Loft.H; j++) {
                if ((i % 2 == 0 && j % 2 ==1)||(i % 2 == 1 && j % 2 ==0)) {
                    g.fillRect(20 * i + 5, 20 * j + 5, 20, 20);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
